repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.2.125'
    hooks:
    - id: checkov
      verbose: true
      args: [
        --compact,
        --quiet,
        --framework, "github_actions"
      ]