name: Pre-Commit framework.
description: Verify the pre-commit framework was used properly by developers.
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax (like 3.x) or the exact Python version
        python-version: '3.9.4'

    - name: Run pre-commit framework as the developer should run it
      run: sudo ./scripts/install.sh && sudo ./scripts/run.sh
      shell: bash
