name: Pre-Commit framework.
description: Verify the pre-commit framework was used properly by developers.
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: .
        framework: terraform 
        soft_fail: true
        quiet: true # display only failed checks

