name: Actions Release CI
run-name: Actions Release CI

permissions:
  contents: write
  issues: read

on:
  push:
    branches: [main]

jobs:

  prerequisites:
    name: format data for pre_commit input
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.format.outputs.files_diff }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get diff with base branch
        id: diff
        uses: tj-actions/changed-files@v32
        with:
          separator: "\n"

      - name: extract only changed folders
        id: format
        env:
          DIFFS: ${{ steps.diff.outputs.all_changed_files }}
        run: |
          echo "::set-output name=files_diff::$(echo "$DIFFS" | tr '\n' ' ')"

  pre_commit:
    name: Pre-Commit
    needs: [prerequisites]
    uses: ./.github/workflows/_pre_commit.yml
    with:
      pre-commit-hooks: checkov
      pre-commit-files: ${{ needs.prerequisites.outputs.changed_files }}

  release:
    name: Semantic release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: sem release
        id: rc
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0
          extra_plugins: |
            conventional-changelog-conventionalcommits@^5.0.0
            @semantic-release/git@^10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: release info
        run: |
          echo new_release_published - ${{ steps.rc.outputs.new_release_published }}
          echo new_release_version - ${{ steps.rc.outputs.new_release_version }}
          echo last_release_version - ${{ steps.rc.outputs.last_release_version }}
          echo new_release_major_version - ${{ steps.rc.outputs.new_release_major_version }}
          echo new_release_minor_version - ${{ steps.rc.outputs.new_release_minor_version }}
      
      - name: create major/minor release tag
        if: steps.rc.outputs.new_release_published == 'true'
        env:
          MAJOR: ${{ steps.rc.outputs.new_release_major_version }}
          MINOR: ${{ steps.rc.outputs.new_release_minor_version }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "github-bot"
          git tag -fa "v$MAJOR" -m "Update v$MAJOR tag"
          git tag -fa "v$MAJOR.$MINOR" -m "Update v$MAJOR.$MINOR tag"
          git push origin "v$MAJOR" --force
          git push origin "v$MAJOR.$MINOR" --force
