name: Actions PR CI
run-name: Actions PR CI

permissions:
  contents: write
  issues: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:

  pre_commit:
    name: Pre-Commit
    uses: ./.github/workflows/_pre_commit.yml
    with:
      pre-commit-hooks: checkov