# DESCRIPTION:
#  A workflow used by both: code and CI repositories for verifying 
#  if PR titles matches conventional commits strategy.
# END

name: Lint PR Title

permissions:
  pull-requests: read

on:
  workflow_call:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title matches conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
