name: (sub) PR CI

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      do_apply:
        description: When set to true runs also apply
        type: boolean
        default: false
      indepotency:
        description: When set to true runs plan to on already applied configuration
        type: boolean
        default: true
      max_parallel:
        description: Maximum parallel jobs in matrix strategy
        type: number
        default: 10
      tf_version:
        description: A space delimited list of TF versions used to run the code with
        type: string
        default: latest
      cloud:
        description: "Decide against which public cloud the code will be run. Possible values: azure, aws, gcp"
        type: string
        required: true

jobs:
  pre_commit:
    name: Pre-Commit
    uses: ./.github/workflows/_pre_commit.yml


  tf_prereqs:
    name: terraform modules discovery
    runs-on: ubuntu-latest
    outputs:
      validate_paths: ${{ steps.format.outputs.dir_diff }}
      plan_paths: ${{ steps.deps.outputs.examples }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get diff with base branch
        id: diff
        uses: tj-actions/changed-files@v32
        with:
          separator: "\n"
          files: |
            modules/**/*.tf
            examples/**/*.tf

      - name: extract only changed folders
        id: format
        env:
          DIFFS: ${{ steps.diff.outputs.all_changed_files }}
        run: |
          echo "::set-output name=dir_diff::$(echo -n "$DIFFS" | sed -E "s/^(modules|examples)\/(.+)\/.*$/\1\/\2/"  | tr '\n' ',')"

      - name: discover module->example dependencies
        id: deps
        env:
          DIFFS: ${{ steps.format.outputs.dir_diff }}
        shell: bash
        run: |
          if [ "$DIFFS" ]; then
            EXAMPLES_DISCOVERY=$(for M in $(echo "$DIFFS" | tr ',' '\n' | grep modules); do
              echo $(grep -rl "$M" examples/*/*.tf | sed -E "s/^(examples\/.*)\/.*$/\1/g")
            done | sort -u | awk NF)

            if [ "$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | grep examples)" ]; then
              EXAMPLES_COMBINED=$(echo "$(echo $EXAMPLES_DISCOVERY | tr ' ' ','),$DIFFS" | tr ',' '\n' | awk NF | grep examples | sort -u)
              echo "::set-output name=examples::$(echo -n $EXAMPLES_COMBINED | tr ' ' ',')"
            fi
          fi


  validate:
    name: validate all changed modules
    needs: [tf_prereqs]
    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
    uses: ./.github/workflows/_tf_validate.yml
    with:
      tf_version: ${{ inputs.tf_version }}
      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}


  branch_protection_junction:
    name: junction point for branch protection
    needs:
      - validate
      - pre_commit
    if: always()
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: check statuses of other jobs
        uses: technote-space/workflow-conclusion-action@v3

      - name: branch protection check validation point
        run: | 
          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
