name: (sub) PR CI

permissions:
  contents: read

on:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-Commit
    uses: ./.github/workflows/_pre_commit.yml


  checkov:
    name: Checkov
    uses: ./.github/workflows/_checkov.yml


  tf_prereqs:
    name: terraform modules discovery
    runs-on: ubuntu-latest
    outputs:
      validate_paths: ${{ steps.format.outputs.dir_diff }}
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get diff with base branch
        id: diff
        uses: tj-actions/changed-files@v31
        with:
          separator: "\n"
          files: |
            modules/**/*.tf
            examples/**/*.tf

      - name: extract only changed folders
        id: format
        env:
          DIFFS: ${{ steps.diff.outputs.all_changed_files }}
        run: |
          echo "::set-output name=dir_diff::$(echo -n "$DIFFS" | sed -E "s/^(modules|examples)\/(.+)\/.*$/\1\/\2/"  | tr '\n' ',')"


  validate:
    name: validate all changed modules
    needs: [tf_prereqs]
    if: ${{ needs.tf_prereqs.outputs.validate_paths != '' }}
    uses: ./.github/workflows/_tf_validate.yml
    with:
      tf_version: 0.15 1.0 1.1 1.2 1.3
      paths: ${{ needs.tf_prereqs.outputs.validate_paths }}


  branch_protection_junction:
    name: junction point for branch protection
    needs:
      - validate
      - pre-commit
      - checkov
    if: always()
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: check statuses of other jobs
        uses: technote-space/workflow-conclusion-action@v3

      - name: branch protection check validation point
        run: | 
          if [[ "$WORKFLOW_CONCLUSION" == "failure" ]]; then exit 1; fi
