name: Pre-Commit update
run-name: "Update Pre-Commit dependencies"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - pre-commit-dependencies-update
  # schedule:
  #   - cron: figure out how often we woud like to release

jobs:
  update:
    name: "Update Pre-Commit dependencies"
    uses: ./.github/workflows/_pre-commit-update.yml
    with:
      update_branch: some-update-branch

  pre-commit:
    name: Run Pre-Commit with the udpated config
    needs: [update]
    if: needs.update.outputs.pr_operation == 'created' || needs.update.outputs.pr_operation == 'updated'
    uses: ./.github/workflows/_pre_commit.yml
    with:
      pre-commit-hooks: checkov
      checkout-branch: some-update-branch

  comment-pr:
    name: Give comment on the PR if pre-commit failed
    needs: [pre-commit, update]
    if: always() && (needs.pre-commit.result == 'failure' || needs.pre-commit.result == 'success')
    uses: ./.github/workflows/_comment_pr.yml
    with:
      pr_number: ${{ needs.update.outputs.pr_number }}
      job_result: ${{ needs.pre-commit.result }}