name: Pre-Commit update

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      script_ref:
        description: Branch/TAG to download the Pre Commit dependencies update script
        type: string
        default: main

jobs:
  update:
    name: "Update Pre-Commit dependencies"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: try python
        shell: python
        run: print("ehlo")
      # - name: checkout repository
      #   uses: actions/checkout@v3

      # - name: download the python scripts
      #   shell: bash
      #   env:
      #     FILES: poetry.toml pre-commit-update.py pyproject.toml
      #   run: |
      #     mkdir -p .github/scripts/
      #     cd .github/scripts/
      #     for F in ${FILES[*]}; do
      #       URL="https://raw.githubusercontent.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/${{ inputs.script_ref }}/.github/scripts/${F}"
      #       curl -s -S -f "$URL" -o "$F"
      #     done
      #     ls -l

      # - name: install Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.11

      # - name: install Poetry
      #   uses: Gr1N/setup-poetry@v8
      #   with: 
      #     poetry-version: 1.4.2

      # - name: run the update script
      #   run: | 
      #     cd .github/scripts/
      #     poetry install
      #     poetry run python ./pre-commit-update.py

      # - name: create pull request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     add-paths: .pre-commit-config.yaml
      #     branch: pre-commit-dependencies-update
      #     commit-message: "[chore] pre-commit-dependencies-update"
      #     title: "[chore] pre-commit-dependencies-update"
