name: Pre-Commit update

permissions:
  contents: read

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '0 1 1-7 * 1' # this means every 1st Monday of every month

jobs:
  update:
    name: "Update Pre-Commit dependencies"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install Python requirements
        shell: bash
        run: python -m pip install pyyaml==6.0 requests==2.31

      - name: run the update script
        shell: python
        run: | 
          from os import environ
          import yaml
          import requests

          pre_commit_config_path = "./.pre-commit-config.yaml"

          with open(pre_commit_config_path, "r") as pre_commit:
              try:
                  pre_commit_config = yaml.safe_load(pre_commit)
              except yaml.YAMLError as exc:
                  print(exc)
                  exit(1)
          
          for repo in pre_commit_config['repos']:
              repo_url = repo['repo'].replace('.git','') if '.git' in repo['repo'] else repo['repo']
              release = repo['rev']
              headers = {'Accept': 'application/json'}
              resp = requests.get(f"{repo_url}/refs?type=tag", headers=headers)
              if resp.status_code == requests.codes.ok:
                  latest_release = resp.json()['refs'][0]
                  if release != latest_release:
                      print(f'{repo_url} needs to be updated to {latest_release}, currently at {release}')
                      repo['rev'] = latest_release
              
          with open(pre_commit_config_path, 'w') as pre_commit:
              yaml.dump(pre_commit_config, pre_commit, default_flow_style=False)

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: .pre-commit-config.yaml
          branch: pre-commit-dependencies-update
          commit-message: "[chore] pre-commit-dependencies-update"
          title: "[chore] pre-commit-dependencies-update"
